"""init

Revision ID: 01719be0fda7
Revises: fa47732f3368
Create Date: 2025-03-23 16:24:55.227758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01719be0fda7'
down_revision: Union[str, None] = 'fa47732f3368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meters', sa.Column('meter_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'meters', ['meter_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meters', type_='unique')
    op.drop_column('meters', 'meter_number')
    # ### end Alembic commands ###
