"""init

Revision ID: 07e841e72d87
Revises: cc54f8b45553
Create Date: 2025-03-19 11:05:21.524894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07e841e72d87'
down_revision: Union[str, None] = 'cc54f8b45553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('square', sa.DECIMAL(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn_uk', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('inn_uk')
    )
    op.drop_table('real_estate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_estate',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('square', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inn_uk', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='real_estate_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='real_estate_pkey'),
    sa.UniqueConstraint('account_number', name='real_estate_account_number_key'),
    sa.UniqueConstraint('inn_uk', name='real_estate_inn_uk_key')
    )
    op.drop_table('properties')
    # ### end Alembic commands ###
