"""init

Revision ID: 44dd3c0debdf
Revises: 4955e5c0f205
Create Date: 2025-03-20 11:01:17.710341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44dd3c0debdf'
down_revision: Union[str, None] = '4955e5c0f205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'properties', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.drop_constraint('users_last_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_last_name_key', 'users', ['last_name'])
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'user_id')
    # ### end Alembic commands ###
