"""init

Revision ID: 4955e5c0f205
Revises: 24b98de287a1
Create Date: 2025-03-20 10:43:37.759795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4955e5c0f205'
down_revision: Union[str, None] = '24b98de287a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'square',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'square',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
