"""init

Revision ID: 960870a8ec0b
Revises: cafbacd9b5cc
Create Date: 2025-04-19 21:12:03.416437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960870a8ec0b'
down_revision: Union[str, None] = 'cafbacd9b5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_readings')
    op.add_column('receipts', sa.Column('paid', sa.Boolean(), nullable=False))
    op.alter_column('tariffs', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tariffs', 'rate',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('receipts', 'paid')
    op.create_table('receipt_readings',
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reading_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], name='receipt_readings_reading_id_fkey'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name='receipt_readings_receipt_id_fkey'),
    sa.PrimaryKeyConstraint('receipt_id', 'reading_id', name='receipt_readings_pkey')
    )
    # ### end Alembic commands ###
