"""init

Revision ID: b36f8ac4a1a3
Revises: 27194dc30809
Create Date: 2025-03-23 14:30:43.162524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36f8ac4a1a3'
down_revision: Union[str, None] = '27194dc30809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('meters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('meters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='meters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tariff', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name='readings_meter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='readings_pkey')
    )
    # ### end Alembic commands ###
