"""init

Revision ID: b543b7f2cb1f
Revises: 1c42389c4e41
Create Date: 2025-03-23 21:14:23.175659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b543b7f2cb1f'
down_revision: Union[str, None] = '1c42389c4e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('current_value', sa.Numeric(), nullable=False))
    op.add_column('readings', sa.Column('previous_value', sa.Numeric(), nullable=True))
    op.drop_column('readings', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('readings', 'previous_value')
    op.drop_column('readings', 'current_value')
    # ### end Alembic commands ###
