"""init

Revision ID: d4d681e67a87
Revises: 192fb10c60bb
Create Date: 2025-04-20 11:45:48.851828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d681e67a87'
down_revision: Union[str, None] = '192fb10c60bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'readings', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.drop_column('readings', 'receipt_id')
    # ### end Alembic commands ###
