"""init

Revision ID: fb722c6286eb
Revises: 20e30592da50
Create Date: 2025-04-19 23:56:55.423927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb722c6286eb'
down_revision: Union[str, None] = '20e30592da50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipts_id', table_name='receipts')
    op.drop_table('receipts')
    op.add_column('payments', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    op.add_column('payments', sa.Column('paid', sa.Boolean(), nullable=False))
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_receipt_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'receipt_id')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payments_receipt_id_fkey', 'payments', 'receipts', ['receipt_id'], ['id'])
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['id'])
    op.drop_column('payments', 'paid')
    op.drop_column('payments', 'transaction_date')
    op.create_table('receipts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='receipts_property_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='receipts_pkey'),
    sa.UniqueConstraint('transaction_number', name='receipts_transaction_number_key')
    )
    op.create_index('ix_receipts_id', 'receipts', ['id'], unique=False)
    # ### end Alembic commands ###
